# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :alpha_lane do
    build_app(
      workspace: "FastLaneBuildConfigTest.xcworkspace",
      configuration: "Alpha",
      scheme: "FastLaneBuildConfigTest copy",
      silent: true,
      clean: true,
      output_name: "my-app.ipa"
    )
  end
end

platform :ios do
  desc "Description of what the lane does"
  lane :dev_lane do
    build_app(
      workspace: "FastLaneBuildConfigTest.xcworkspace",
      configuration: "Dev",
      scheme: "FastLaneBuildConfigTest copy", ## DEV 환경 예시
      silent: true,
      clean: true,
      output_name: "my-app.ipa"
    )
  end
end

platform :ios do
  desc "Description of what the lane does"
  lane :beta_lane do
    build_app(
      workspace: "FastLaneBuildConfigTest.xcworkspace",
      configuration: "Beta",
      scheme: "FastLaneBuildConfigTest",
      silent: true,
      clean: true,
      output_name: "my-app.ipa" 
    )
  end
end

